[project]
name = "fuck-zjooc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddddocr>=1.5.6",
    "html2text>=2024.2.26",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
